### ISSUE TITLE
Overlapped sa borrow kits

### ISSUE THREAD

**Issue by Marygracelastrollo** [nameoftheuser1/nasecure#18]
![Screenshot 2024-08-29 191629](https://github.com/user-attachments/assets/49e7ee44-e80d-454e-8901-f22d7f18ff0e)
sabi ng strikto naming consultant ayusin layout dapat hindi nag ooverlapped

**Comment by nameoftheuser1** [comment]
nilagay ko lang siya sa top 

![image](https://github.com/user-attachments/assets/250b4555-000b-483d-8706-9ddc3d07be84)
