### ISSUE TITLE
courses

### ISSUE THREAD

**Issue by Marygracelastrollo** [nameoftheuser1/nasecure#26]
![Screenshot (738)](https://github.com/user-attachments/assets/dff54014-2435-4198-a0be-06b14bc180d0)
pag pinipindot ang courses nag eerror

**Comment by nameoftheuser1** [comment]
run mo po muna ang 

`php artisan migrate:fresh`

kasi po nabago ang database ganyan po talaga pag may binabago sa database
run nyo nalang po ulit ang

`php artisan db:seed --class AdminSeeder`

at 

`php artisan db:seed --class KitSeeder`
